Blogg/posts/forms.py
from flask_wtf.file import FileAllowed, FileField
from flask_wtf.form import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class PostForm(FlaskForm):
    title=StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    post_picture = FileField('Add a post picture', validators=[FileAllowed(['jpg', 'png'])])
    submit = SubmitField('Post')

Blogg/home/routes.py
from flask import Blueprint, request, render_template
from Blogg.models import Post

home = Blueprint('home', __name__)


#routes for different pages/functionality on the website
@home.route("/")
@home.route("/homepage")
def homepage():
    #to get the page number from the url query
    page = request.args.get('page', 1, type=int)

    #paginate doesn't send all the queries back. It divides the posts in pages
    #order by newest
    post = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('homepage.html', post=post)

@home.route("/about")
def about():
    return render_template('about.html', title='About')

Blogg/main/routes.py
from flask import Blueprint, request, render_template
from Blogg.models import Post

main = Blueprint('main', __name__)


#routes for different pages/functionality on the website
@main.route("/")
@main.route("/home")
def home():
    #to get the page number from the url query
    page = request.args.get('page', 1, type=int)

    #paginate doesn't send all the queries back. It divides the posts in pages
    #order by newest
    post = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('home.html', post=post)

@main.route("/about")
def about():
    return render_template('about.html', title='About')

Blogg/posts/routes.py
from Blogg.posts.forms import PostForm
from flask import Blueprint,render_template, url_for, redirect, flash, request, abort
from Blogg import db
from flask_login import current_user, login_required
from Blogg.models import Post
from Blogg.posts.utils import update_pic

posts = Blueprint('posts', __name__)

@posts.route("/post/new", methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        if form.post_picture.data:
            post_pic = update_pic(form.post_picture.data)
            post = Post(title=form.title.data, content=form.content.data, post_picture=post_pic, author=current_user)
        else:
            post = Post(title=form.title.data, content=form.content.data, author=current_user)
        
        db.session.add(post)
        db.session.commit()
        flash(f'Your post has been created! ', 'success')
        return redirect(url_for('home.homepage'))
    return render_template('create_post.html', title='New Post', legend='New Post', form=form)

@posts.route("/post/<int:post_id>")
def post (post_id):
    #if the post doesnt exist then show a 404 error
    post = Post.query.get_or_404(post_id)
    return render_template('post.html', title=post.title, post=post)

@posts.route("/post/<int:post_id>/update", methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get_or_404(post_id)

    if post.author != current_user:
        abort(403)

    form = PostForm()

    if form.validate_on_submit():
        if form.post_picture.data:
            post_pic = update_pic(form.post_picture.data)
            post.post_picture=post_pic
        post.title = form.title.data
        post.content=form.content.data
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('posts.post', post_id=post.id))

    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('create_post.html', title='Update Post', legend='Update Post', form=form)

@posts.route("/post/<int:post_id>/delete", methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    if post.author != current_user:
        abort(403)

    db.session.delete(post)
    db.session.commit()
    flash('Your post has been deleted!', 'success')
    return redirect(url_for('home.homepage'))

Blogg/users/routes.py
from Blogg.users.utils import send_reset_email, update_pic
from Blogg import  db, bcrypt
from Blogg.models import Post, User
from Blogg.users.forms import (
        LoginForm,
        RegistrationForm, 
        RequestResetForm, 
        ResetPasswordForm, 
        UpdateAccountForm
    )
from flask import (Blueprint, 
        render_template, 
        url_for, 
        redirect, 
        flash, 
        request
    )
from flask_login import current_user, login_user, login_required, logout_user

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    #check if user is already logged in
    if current_user.is_authenticated:
        return redirect(url_for('home.homepage'))
    form= RegistrationForm()
    if form.validate_on_submit():
        #create a hashed pass for the user and adding the details onto the table
        hash_pass = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hash_pass)
        db.session.add(user)
        db.session.commit()
        flash(f'Account created for {form.username.data}! You can login now.', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():

    if current_user.is_authenticated:
        return redirect(url_for('home.homepage'))
    form= LoginForm()
    if form.validate_on_submit():
        #match the given password with the hashed password saved in table
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            flash(f'{form.email.data} logged in succesfully!', 'success')
            next_page = request.args.get('next')
            return redirect (next_page) if next_page else redirect(url_for('home.homepage'))
        else:
            flash('Login Unsuccessful! Please check email and password.', 'danger')

    return render_template('login.html', title='Log In', form=form)

@users.route("/logout")
def logout():
    #using logout of Flask_login
    logout_user()
    return redirect(url_for('home.homepage'))

@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    profile_img = url_for('static', filename='pfp/'+ current_user.profile_img)
    form=UpdateAccountForm()
    if form.validate_on_submit():
        if form.pic.data:
            pic_newname = update_pic(form.pic.data)
            current_user.profile_img = pic_newname
        #we cange the details of current user
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your info has been updated!', 'success')

        # this is to make sure we dont submit the form when the page reloads. It sends a 'GET' request
        return redirect (url_for('users.account'))

    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    #checking
    return render_template('account.html', title='Account', profile_img=profile_img, form=form)

@users.route("/user/<string:username>")
def user_posts(username):
    #to get the page number from the url query
    page = request.args.get('page', 1, type=int)

    user = User.query.filter_by(username=username).first_or_404()
    #paginate doesn't send all the queries back. It divides the posts in pages
    #order by newest
    # \ to break up to other line 
    post = Post.query.filter_by(author=user)\
        .order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('user_posts.html', post=post, user=user)

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    #check if user is already logged in
    if current_user.is_authenticated:
        return redirect(url_for('home.homepage'))

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been send to reset your password', 'info')
        return redirect(url_for('users.login'))

    return render_template('reset_request.html', title='Reset Password', form=form)



@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    #check if user is already logged in
    if current_user.is_authenticated:
        return redirect(url_for('home.homepage'))

    user = User.verify_reset_token(token)

    if user is None:
        flash('Token is invalid or expired', 'warning')
        return redirect(url_for('users.reset_request'))
    
    form = ResetPasswordForm()
    if form.validate_on_submit():
        #create a hashed pass for the user and adding the details onto the table
        hash_pass = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hash_pass
        db.session.commit()
        flash(f'Password for {user.username} has been updated! You can login now.', 'success')
        return redirect(url_for('users.login'))

    return render_template('reset_token.html', title='Reset Password', form=form)

Blogg/templates/about.html
{% extends "layout.html" %}
{% block content %}
      <h1>About</h1>
      <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.
      </p>
{% endblock content %}

Blogg/templates/create_post.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">{{legend}}</legend>
                <div class="form-group">
                    {{ form.title.label(class="form-control-label")}}

                    {% if form.title.errors %}
                    {{form.title(class="form-control form-control-lg is-invalid")}}

                    <div class="invalid-feedback">
                        {%for error in form.title.errors%}
                        <span>{{error}}</span>
                        {%endfor%}
                    </div>

                    {%else%}
                    {{ form.title(class="form-control form-control-lg")}}
                    {%endif%}
                </div>
                <div class="form-group">
                    {{ form.content.label(class="form-control-label")}}
                    {% if form.content.errors %}
                    {{form.content(class="form-control form-control-lg is-invalid")}}
                    <div class="invalid-feedback">
                        {%for error in form.content.errors%}
                        <span>{{error}}</span>
                        {%endfor%}
                    </div>

                    {%else%}
                    {{ form.content(class="form-control form-control-lg")}}
                    {%endif%}
                </div>
                <div class="form-group mt-2">
                    {{ form.post_picture.label()}}
                    <br>
                    {{ form.post_picture(class="form-control-file")}}
                    {% if form.post_picture.errors %}
                        {% for error in form.post_picture.errors %}
                        <!-- file type errors are different thats why we used text-danger class of bootstrap for color-->
                        <span class="text-danger">{{error}}</span></br>
                        {%endfor%}
                    {%endif%}
                </div>
            </fieldset>
            <div class="form-group mt-4">
                {{form.submit(class="btn btn-outline-primary")}}
            </div>
        </form>
    </div>
{% endblock content %}

Blogg/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <div class="row welcome text-center">
            <div class="col-12">
                <h1 class="display-4">Built with</h1>
            </div>
        </div>
        <div id="slides" class="carousel slide carousel-fade carousel-dark slide " data-bs-ride="carousel">
            <div class="carousel-indicators">
            <button type="button" data-bs-target="#slides" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#slides" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#slides" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="4000">
                <img src="{{url_for('static', filename='pfp/Flask_logo.png') }}" class="d-block w-100 h-60" alt="...">
            </div>

            <div class="carousel-item " data-bs-interval="3000">
                <img src="{{url_for('static', filename='pfp/sqlalchemy.jpg') }}" class="d-block w-100 h-60" alt="...">
                
            </div>
            <div class="carousel-item" data-bs-interval="3000">
                <img src="{{url_for('static', filename='pfp/bootstrap.png') }}" class="d-block w-100 h-60" alt="...">

            </div>
            </div>
        </div>
    </div>
    <hr class="mt-5 mb-5">

        {% for posts in post.items %}
        <div class="card mb-3">
            <div class="row no-gutters">
              <div class="col-md-4 xs-6">
                <img src="{{url_for('static', filename='post_pics/'+ posts.post_picture)}}" class="card-img full-size" alt="{{posts.post_picture}}">
              </div>
              <div class="col-md-8 xs 6">
                <div class="card-body">
                    <div>
                        <img class="rounded-circle article-img" src="{{url_for('static', filename='pfp/'+posts.author.profile_img)}}">
                        <a class="mr-2" href="{{url_for('users.user_posts', username=posts.author.username)}}">{{ posts.author.username }}</a>
                    </div>
                    <hr>
                  <h5 class="card-title pb-2"><a class="article-title" href="{{url_for('posts.post', post_id=posts.id)}}">{{ posts.title }}</a></h5>
                  
                  <p class="card-text" style="max-height: 100px; overflow:hidden;">{{ posts.content }}</p>
                  <p class="card-text article-content"><small class="text-muted">{{ posts.date_posted.strftime('%Y-%m-%d') }}</small></p>
                </div>
              </div>
            </div>
          </div>           
           
        {% endfor %}
         <!-- paginate.iter_pages  divides the pages intogroups separated by none, e.g. 1 2 none 4 5 6 none 8-->
         <!-- edge parameter - number of pages next to 'none'-->
        {% for page_num in post.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}  
            {% if page_num %}
                <!--If the page number is the same as the current page given by post.page(method of paginate object)-->
                {% if post.page == page_num %}
                    <a class="btn btn-info mb-4"href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4"href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
{% endblock content %}

Blogg/templates/homepage.html
{% extends "layout.html" %}
{% block content %}
    <div class="container">
        <div class="row welcome text-center">
            <div class="col-12">
                <h1 class="display-4">Built with</h1>
            </div>
        </div>
        <div id="slides" class="carousel slide carousel-fade carousel-dark slide " data-bs-ride="carousel">
            <div class="carousel-indicators">
            <button type="button" data-bs-target="#slides" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#slides" data-bs-slide-to="1" aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#slides" data-bs-slide-to="2" aria-label="Slide 3"></button>
            </div>
            <div class="carousel-inner">
            <div class="carousel-item active" data-bs-interval="4000">
                <img src="{{url_for('static', filename='pfp/Flask_logo.png') }}" class="d-block w-100 h-60" alt="...">
            </div>

            <div class="carousel-item " data-bs-interval="3000">
                <img src="{{url_for('static', filename='pfp/sqlalchemy.jpg') }}" class="d-block w-100 h-60" alt="...">
                
            </div>
            <div class="carousel-item" data-bs-interval="3000">
                <img src="{{url_for('static', filename='pfp/bootstrap.png') }}" class="d-block w-100 h-60" alt="...">

            </div>
            </div>
        </div>
    </div>
    <hr class="mt-5 mb-5">

        {% for posts in post.items %}
        <div class="card mb-3">
            <div class="row no-gutters">
              <div class="col-md-4 xs-6">
                <img src="{{url_for('static', filename='post_pics/'+ posts.post_picture)}}" class="card-img full-size" alt="{{posts.post_picture}}">
              </div>
              <div class="col-md-8 xs 6">
                <div class="card-body">
                    <div>
                        <img class="rounded-circle article-img" src="{{url_for('static', filename='pfp/'+posts.author.profile_img)}}">
                        <a class="mr-2" href="{{url_for('users.user_posts', username=posts.author.username)}}">{{ posts.author.username }}</a>
                    </div>
                    <hr>
                  <h5 class="card-title pb-2"><a class="article-title" href="{{url_for('posts.post', post_id=posts.id)}}">{{ posts.title }}</a></h5>
                  
                  <p class="card-text" style="max-height: 100px; overflow:hidden;">{{ posts.content }}</p>
                  <p class="card-text article-content"><small class="text-muted">{{ posts.date_posted.strftime('%Y-%m-%d') }}</small></p>
                </div>
              </div>
            </div>
          </div>           
           
        {% endfor %}
         <!-- paginate.iter_pages  divides the pages intogroups separated by none, e.g. 1 2 none 4 5 6 none 8-->
         <!-- edge parameter - number of pages next to 'none'-->
        {% for page_num in post.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}  
            {% if page_num %}
                <!--If the page number is the same as the current page given by post.page(method of paginate object)-->
                {% if post.page == page_num %}
                    <a class="btn btn-info mb-4"href="{{ url_for('home.homepage', page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4"href="{{ url_for('home.homepage', page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
{% endblock content %}

Blogg/templates/layout.html
<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">    
    <link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}">
    
    {% if title %}
    <title>Blogg - {{title}}</title>
    {% else%}
    <title>Blogg</title>
    {% endif %}

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
  </head>
  <body>

    <header class="site-header">

        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <div class="container">

            <a class="navbar-brand" href="{{url_for('home.homepage') }}">Blogg</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
              </button>

            <div id="navbarResponsive" class="collapse navbar-collapse">

              <div class="navbar-nav me-auto text-center ">
                <a id="len1" class="nav-item nav-link hoverable "  href="{{ url_for('home.homepage')}}">Homepage</a>
                <a id="len2" class="nav-item nav-link hoverable " href="{{ url_for('home.about') }}">About</a>
              </div>

              <div class="navbar-nav text-center ">
                {% if current_user.is_authenticated %}
                   
                        <a id="len3" class="nav-item nav-link  hoverable" href="{{ url_for('users.account') }}">Account</a>
                    
                        <a id="len4" class="nav-item nav-link hoverable" href="{{ url_for('posts.new_post') }}">New Post</a>                    
                    
                        <a id="len5" class="nav-item nav-link hoverable" href="{{ url_for('users.logout') }}">LogOut</a>
                   

                {%else%}
                    <a id="len3" class="nav-item nav-link hoverable " href="{{ url_for('users.login') }}">Login</a>
                
                    <a id="len4" class="nav-item nav-link hoverable  " href="{{ url_for('users.register') }}">Register</a>                    
                
                {%endif%}

              </div>
            </div>
            </div>
        </nav>
        

    </header>
    

    </div>
    <main role="main" class="container">
        <div class="row">
            <div class="col-md-8">
                {% with messages=get_flashed_messages(with_categories=true)%}
                    {%if messages%}
                        {%for category, message in messages%}
                        <div class="alert alert-{{category}}">
                            {{message}}
                        </div>
                        {%endfor%}
                    {%endif%}
                {%endwith%}
                {% block content %}
                {% endblock content %}
            </div>

            <div class="card" style="width: 18rem; height:auto;" >
                <img src="{{url_for('static', filename='post_pics/default_post.jpeg')}}" class="card-img-top" alt="Default Pic">
                <div class="card-body">
                  <h5 class="card-title">Pinned Post</h5>
                  <p style="max-height:150px; overflow:hidden;"class="card-text">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s...</p>
                  <a href="{{ url_for('home.homepage')}}" class="btn btn-primary">Read more</a>
                </div>
              </div>
        </div>

    </main>
   
  </body>
</html>

Blogg/templates/login.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log In</legend>
            <div class="form-group">
                {{ form.email.label(class="form-control-label")}}

                {% if form.email.errors %}
                {{form.email(class="form-control form-control-lg is-invalid", placeholder="youremail@example.com")}}
                <div class="invalid-feedback">
                    {%for error in form.email.errors%}
                    <span>{{error}}</span>
                    {%endfor%}
                </div>

                {%else%}
                {{ form.email(class="form-control form-control-lg", placeholder="youremail@example.com")}}
                {%endif%}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label")}}
                {% if form.password.errors %}
                {{form.password(class="form-control form-control-lg is-invalid")}}
                <div class="invalid-feedback">
                    {%for error in form.password.errors%}
                    <span>{{error}}</span>
                    {%endfor%}
                </div>

                {%else%}
                {{ form.password(class="form-control form-control-lg")}}
                {%endif%}
            </div>
            <div class="form-check">
                {{form.remember(class="form-check-input")}}
                {{form.remember.label(class="form-check-label")}}
            </div>

            <div class="pt-3">
                <a class="ml-2" href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
            </div>

            <div class="form-group mt-4">
                {{form.submit(class="btn btn-outline-primary")}}
            </div>


        </fieldset>

        <div class="border-top pt-3">
            <small class="text-muted">
                Need an account?? <a class="ml-2" href="{{url_for('users.register')}}">Sign Up</a>
            </small>
        </div>
    </form>
</div>
{% endblock content %}

Blogg/templates/post.html
{% extends "layout.html" %}
{% block content %}           
    <article class="media content-section">
        <!--User Profile-->
        <img class="rounded-circle article-img" src="{{url_for('static', filename='pfp/'+post.author.profile_img)}}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" href="{{url_for('users.user_posts', username=post.author.username)}}">{{ post.author.username }}</a>
                <!--To display just the YMD-->
                <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                {% if post.author == current_user%}
                <div>
                    <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{{ url_for('posts.update_post', post_id=post.id)}}">Update Post</a>
                    <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
                </div>
                {%endif%}
            </div>
            <div class="card mt-3">
                <img src="{{url_for('static', filename='post_pics/'+ post.post_picture)}}" class="card-img-top" alt="Post Picture" style="max-height: 600px;">
                <div class="card-body">
                  <h5 class="card-title">{{ post.title }}</h5>
                  <p class="card-text">{{ post.content }}</p>
                </div>
              </div>
        </div>
    </article>
    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            <form action="{{url_for('posts.delete_post', post_id=post.id)}}" method="POST">
                <input class="btn btn-danger" type="submit" value="Delete">
            </form>
            </div>
        </div>
        </div>
    </div>
  
{% endblock content %}

Blogg/templates/user_posts.html
{% extends "layout.html" %}
    {% block content %}
    <h1 class="mb-3">Posts by {{ user.username }}  ({{post.total}})</h1>
        {% for posts in post.items %}        
            <div class="card mb-3">
                <div class="row no-gutters">
                <div class="col-md-4 xs-6">
                    <img src="{{url_for('static', filename='post_pics/'+ posts.post_picture)}}" class="card-img full-size" alt="{{posts.post_picture}}">
                </div>
                <div class="col-md-8 xs 6">
                    <div class="card-body">
                        <div>
                            <img class="rounded-circle article-img" src="{{url_for('static', filename='pfp/'+posts.author.profile_img)}}">
                            <a class="mr-2" href="{{url_for('users.user_posts', username=posts.author.username)}}">{{ posts.author.username }}</a>
                        </div>
                        <hr>
                    <h5 class="card-title pb-2"><a class="article-title" href="{{url_for('posts.post', post_id=posts.id)}}">{{ posts.title }}</a></h5>
                    
                    <p class="card-text" style="max-height: 100px; overflow:hidden;">{{ posts.content }}</p>
                    <p class="card-text article-content"><small class="text-muted">{{ posts.date_posted.strftime('%Y-%m-%d') }}</small></p>
                    </div>
                </div>
                </div>
            </div>           
                
        {% endfor %}
         <!-- paginate.iter_pages  divides the pages intogroups separated by none, e.g. 1 2 none 4 5 6 none 8-->
         <!-- edge parameter - number of pages next to 'none'-->
        {% for page_num in post.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}  
            {% if page_num %}
                <!--If the page number is the same as the current page given by post.page(method of paginate object)-->
                {% if post.page == page_num %}
                    <a class="btn btn-info mb-4"href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
                {% else %}
                    <a class="btn btn-outline-info mb-4"href="{{ url_for('users.user_posts', username=user.username, page=page_num) }}">{{ page_num }}</a>
                {% endif %}
            {% else %}
                ...
            {% endif %}
        {% endfor %}
    {% endblock content %}